"""Turn a WAV file into an obfuscated Python module.

Usage:
    python scripts/embed_wav.py <wav-path> <slot>

``slot`` is any identifier, e.g. ``send``, ``receive``, ``typing_1``,
``typing_2``. For typing variants, use the convention ``typing_<N>`` —
``sounds.py`` auto-discovers all ``_typing_*_data`` modules and picks
randomly between them on each click to avoid repetition.

Output: ``src/flamechat/ui/_<slot>_data.py`` containing the WAV bytes
XOR-scrambled against a fixed key and base64-wrapped. The module exposes
``WAV_BYTES: bytes`` — the plain WAV bytes, decoded lazily on import.

This is obfuscation, not encryption. Goal: someone browsing inside the
installed app bundle can neither find a ``.wav`` file nor a recognisable
``RIFF`` header in the Python file, so they cannot trivially rip the
sound. A determined reverse engineer could still recover it, but that's
true of any scheme where the decode key has to ship with the app.
"""

from __future__ import annotations

import base64
import sys
import textwrap
from pathlib import Path


# The key is intentionally long and non-obvious. Change it if a sound is
# ever leaked so the leaked bytes can't be decoded with the old scheme.
XOR_KEY = b"FlameChat-Obfuscation-Key-2026-Do-Not-Steal"


def xor_bytes(data: bytes, key: bytes) -> bytes:
    klen = len(key)
    return bytes(b ^ key[i % klen] for i, b in enumerate(data))


def chunk_b64(encoded: str, width: int = 76) -> list[str]:
    return textwrap.wrap(encoded, width)


HEADER = '''"""Obfuscated WAV bytes for the "{slot}" sound.

Generated by scripts/embed_wav.py — do not edit by hand. Regenerate by
running the embed script against the source WAV.

The bytes are XOR-scrambled and base64-wrapped. See ui/sounds.py for the
decode path. This is a theft deterrent, not real encryption.
"""

from __future__ import annotations

import base64


_B64 = (
{b64_block}
)

_KEY = {key!r}


def _xor(data: bytes, key: bytes) -> bytes:
    klen = len(key)
    return bytes(b ^ key[i % klen] for i, b in enumerate(data))


WAV_BYTES: bytes = _xor(base64.b64decode(_B64), _KEY)
'''


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    wav_path = Path(sys.argv[1]).expanduser().resolve()
    slot = sys.argv[2].strip().lower()
    if not slot.replace("_", "").isalnum():
        print(
            f"Invalid slot name {slot!r}: use letters, digits and underscores only.",
            file=sys.stderr,
        )
        sys.exit(2)
    if not wav_path.is_file():
        print(f"Not a file: {wav_path}", file=sys.stderr)
        sys.exit(2)

    data = wav_path.read_bytes()
    if data[:4] != b"RIFF":
        print(f"Warning: {wav_path} does not start with RIFF; is it really a WAV?",
              file=sys.stderr)

    scrambled = xor_bytes(data, XOR_KEY)
    encoded = base64.b64encode(scrambled).decode("ascii")
    b64_block = "\n".join(f'    "{line}"' for line in chunk_b64(encoded))

    out_dir = Path(__file__).resolve().parent.parent / "src" / "flamechat" / "ui"
    out_path = out_dir / f"_{slot}_data.py"
    out_path.write_text(
        HEADER.format(slot=slot, b64_block=b64_block, key=XOR_KEY),
        encoding="utf-8",
    )
    size_kb = len(data) / 1024
    print(f"Wrote {out_path.relative_to(out_path.parents[3])} "
          f"({size_kb:.1f} KB source → {len(encoded)/1024:.1f} KB encoded).")


if __name__ == "__main__":
    main()
