"""Obfuscated WAV bytes for the "click" sound.

Generated by scripts/embed_wav.py — do not edit by hand. Regenerate by
running the embed script against the source WAV.

The bytes are XOR-scrambled and base64-wrapped. See ui/sounds.py for the
decode path. This is a theft deterrent, not real encryption.
"""

from __future__ import annotations

import base64


_B64 = (
    "FCUnKx9JaGEjbBknABgHQ3F0aW9vLUplPYEyMLpuLERtLV5vEEwnFTNrbEZsYZWacWsmd2pPkmNi"
    "evNm+GefbE62XnxkMJ/E1N6nug2gcoc3o+OdWZ/0b/WQt0x/eN0MH0OkM/lTpG35fATdUWLgLJLS"
    "huF6uHj5w7pQhpKVE8EaoSuWEXS6hcRnoBiZIz0dA0qpeQNBTE4xYHwgh82nKWPD2qLCouyE36vP"
    "wWuwwoOKn4xBOdYrSCJpOEHOS5la6DPpftwtDidJO7uuhvbGtEWJfsfNspuHvrWPucNsqm9ySid0"
    "MUc4fUQLrUNNWBJdyhOANtDcnWoZp5GvlOKqvXmakKJC009HL2GZ1wZ2QEBFefdZokxLBXNoWgHE"
    "KprB1rPZKhm2h8xTgVveM6KAvIOCvrCRqiC9CG66fGN0EiEQQV5lEmYkHnUitdLRhUlKcajbvaeB"
    "54PQmeyN4qRgjmnRRm3hbm1NlU5fbmAy4WwaM5QuhTmbQk8o/48zzH6F56A4no+QP7XwsyKd/qcB"
    "eM1/H2GKdjh3NG6VWi0+gDzpOiRjWU3hnDG74b6lgPqQg7A1nnWS/91kkG9ti2xLZ2pjqjEBmzw3"
    "ORaVJ7xLcjTYafXA5XCZs5mYxLdFtq+Gv6wBu0CKnmkVbalscXS0bvdx8ysiKT0gam5yRVCMo6KX"
    "vB+YdLfJo4eguIHS0QCcan6yZB51Y3B80YhGUwnaE1wiq1fEOjyQ2iFjngy7g6ZdjFeFSJkodIi1"
    "opKOgz1xunkyaeBX9nmiJQgSk9drkkJugYGzrQKOZ5ZQmXCaY6hWi47YH44LiSiVd3ddk/0rFkC7"
    "JEMjniygSFMhVGd62l1zt5GXRqWH5ZPWkQmcor1vj8GJh5ndZJxw4UL+dOg/ICyFIFR9DkdiiVJQ"
    "zXZGgjyeaZ8rqmaQbPNRiO2YfpXmii+R3NKAaIcn2SFyMktLOzrTZuwldIr5l5S8emOjgwWZbJiz"
    "tQSID4sQZ8+SV2xmTeJ+0DFMKew0eGMXQPFnOVswbI6QzJUfbHCjjZtZ2aGImI3mmaaAC5D2JHJp"
    "uCVeKIA4jlHOIwhz0CPDcehkPLEBlTOX05vdg0Gjf5cigvyd144qawS2sX2Rzm02nj4HY1Rajnv4"
    "Qrth4ZQLlhZkv7pTYPHe+pnnmkyPf49+l1DR8WHNKxo64DTRQb8iAmpvKLRg02CduzyaJprEm4Ga"
    "CL13kBuG35gvaBKTxUnMeTsxPDaGJzFg3UEVijJfnmyobVZtxZdiQjKZlC29lHOMlJO2jL6WSNlb"
    "mmXSQs0JMDxW+CfukfUsR3GjaCBEUZ7DZQ6Ws48nTBOcGolnnSeUQZk9vUGAxM+rMbks8mYVRoZn"
    "glrnY7to3m7uZeRBwmHX0NyXLIytkzeIVpkS1/CcvtHMMffM0kCBKl58UyjxdzRopLmMZUJiAG3x"
    "ii9OWprYhS6ZRpMplPOwUYBmxXTNHymElT5IgHxqWSJglmGYkZFs5LqjZNbSlZ5Yj6qWVoynngXW"
    "e5vi0EDKdDPquustDZAeJcB4sWRSQGhmjmMybPKO77DLmwqLXp8EkhSWdrCyhYPMo8yeLVORx0sl"
    "cexa7GQVaxVt1JKNRqFjCdLjnlyMRZnxjkGVwtCbmXPb3DAPyEhHjy5ibr0uRHODZPdE8WhqZgJp"
    "6XWzTf2bwonGnXOVb5pKsqeAT8k9yZLRDpFjswlxLFFzZeJu8ms6beJBFGN40q2c/Iovnmh2G5hg"
    "LCCcgtb+yabMkLjd0ktvUC3hcmxj5UFmZXJmPGukiRCwH5knjDBhapbBlRKwYoUMyB/JvtdTkFhN"
    "IotqrWpgB25gaBNpvUJVYuMukp3ydYqfWom7lyfQZJ7qLIbMrsNqv6PT95Kw0952/WOpRyJjwGeH"
    "bv9wdUibmcxySp/Aaf+Qg7AJgk7Jw8oM1hWTmrP1ivitRWe+bxVtXm4nQeeeoSqnYL908GIqdPKV"
    "HdFMZGrT88oYzSC7kNLIkmEspYuNn1dEPGKgYClsuHcQStZkzozPYC5pmZFOS36Dd84Rzh3QYpJ+"
    "syB0EVOWZcmTxWyobUBHQ2ffLbhjmnSfYdd1KJFg0sCY09J3zPjKOr8g0ZuRBtOyiSRgDEcFY1hn"
    "F2qFdq5NmWU8cQRggmmzbhO0aYRDzJ/PR9HkkJKzQHSXrQma4Wx8bKttXEEcYost352VdOhjEHUT"
    "bwfSkpiT0wbNXci1uOPQPJEkLYuIw5/quStgjmexarx1yE2BZPhxU2OnaIpurkp6hK7M3M4H06yT"
    "RLNkihes/ZuQk2eTgZLaQxxhMC8uY3Z0HmM9dpdujdJpZZTSF8+XyS27S9MwkbXR8ovTno24a2GH"
    "ZSFpX3ZMT+5kyHB6YTZpG2/jtJuHUs2czX4tB5E2sUqK668YmMOSZpMfkgZCdWH3LP5jBHbCYd11"
    "nm9KLKNlxdKAz73Idbuf0/+RRNJxi0WfLrmqnlplEWjZdVxOemQVcPVjJmhGbpO0A4bbzVPMsdPq"
    "kJKwTYt0rd6YcZNHkqSTh7yAnpst+GNXilFhHHUlbjgs3mcMLcHPZckMRM3S65JM02uL+Z/Quzye"
    "jZteaFB1CE6kZ3lysGDza9BvfUrChtTNuzM/LXuRJbEJimytc5tSk7qScJL6vBqeLtIqY391sWOq"
    "dARuViw8ZBEsbDCvyXlEydIwkBDSzYrnnMK5jZ73mhGX/XT4T8yZ0HO9nhdo0pEiSlx4fTNgMh8t"
    "9pA+seuKAKybm8WSh5JBkuK89Z5NLYZiYXUkYjV1SG49LJhlpC3JMEE2HUQRLeCQVi0Ti5efRbjo"
    "nnFlb5eoi1CwdGYjjLJhsmkNb9dLenjsMi4yMS2GkNexBIvsrUWa2pNwk3SSYrwVnm/SFWJLdaFj"
    "AXU8bhEt52XOLKUwlzatu6XSJZDh0oaKMp5JueWemprYll+LaLDRmUpzVmDdae9uMkpmeEIy6DL2"
    "LWNvS04idFysQpo+kx+TeZJZvFKe5NKMnVJ1dWPIiylvQCyJZXUspDDKydq72y0mkEAtQnS/nyu5"
    "JZ6ym3GX2YvzsU2ZCHNdYUppUm7RtAd57TKzMvMtaG6OTvqLyqzEmmdsJJPNk21DAZ6V0hOd2Yop"
    "Y3V08m9QLSZlsy3iMLE2bESqLXhv4S3ui8ye7rlznvqa3Jd5i76wk5mnjLKeYWnVkaJLL3mDMk8y"
    "ii3/b/BOwXQSUx1lypPpk+uStLypnk7S5p3HikWcaXTgkBEtLGVRLRYwZja+RBktK29nLQJ0amH5"
    "udCe8pp3lwqLqLDhmYGMp557aWBuWksAeawy+jJmLTVvS075dKxTX2W7k6WTXJKovL6eBNKdnd2K"
    "fWPZi5GQt9JQZUstXzA2Nh5E0C00bz0tB3RjYYq5XWGvmsOXV4tCsM2Z94wPnoWW25HNtB558s09"
    "MqAtPG+WTj90UFN5ZXxsUGyFkvy8j5680tudxYrSnAiLk5DZ0qGaVS3Xz8bJWEQuLXhv0i1odDNh"
    "NUZ+YZ6ah5eni6Gw1Zn4jIaez5aokfm0k4ZmMhoyTy0hb2lOV3RoUydlOWxpbGFtibyxnoLSp53R"
    "isWc34tib6DSSWU="
)

_KEY = b'FlameChat-Obfuscation-Key-2026-Do-Not-Steal'


def _xor(data: bytes, key: bytes) -> bytes:
    klen = len(key)
    return bytes(b ^ key[i % klen] for i, b in enumerate(data))


WAV_BYTES: bytes = _xor(base64.b64decode(_B64), _KEY)
